### ISSUE TITLE
Some repos started failing when there is no data in DataFrame

### ISSUE THREAD

**Issue by ChameleonTartu** [jgehrcke/github-repo-stats#17]
For the last few days, I see that some projects started failing:

```
Empty DataFrame
Columns: [clones_total, clones_unique]
Index: []
210428-01:17:49.220 INFO:MainThread: dataframe datetimeindex detail: DatetimeIndex([], dtype='datetime64[ns, UTC]', name='time_iso8601', freq=None)
210428-01:17:49.220 INFO:MainThread: fetch data for views
210428-01:17:49.348 INFO:MainThread: built dataframe for views:
Empty DataFrame
Columns: [views_total, views_unique]
Index: []
210428-01:17:49.349 INFO:MainThread: dataframe datetimeindex detail: DatetimeIndex([], dtype='datetime64[ns, UTC]', name='time_iso8601', freq=None)
210428-01:17:49.350 INFO:MainThread: indices of df_views and df_clones are equal
210428-01:17:49.350 INFO:MainThread: union-merge views and clones
210428-01:17:49.351 INFO:MainThread: df_views_clones:
Empty DataFrame
Columns: [clones_total, clones_unique, views_total, views_unique]
Index: []
210428-01:17:49.352 INFO:MainThread: current working directory: /github/workspace/ChameleonTartu/amazon-mws-fulfillment-inventory-maven
210428-01:17:49.352 INFO:MainThread: write output CSV files to directory: newdata
210428-01:17:49.352 INFO:MainThread: do not write df_views_clones: empty
210428-01:17:49.353 INFO:MainThread: do not write df_referrers_snapshot_now: empty
210428-01:17:49.353 INFO:MainThread: do not write df_paths_snapshot_now: empty
210428-01:17:49.353 INFO:MainThread: done!
+ FETCH_ECODE=0
+ set -e
+ set +x
fetch.py returned with exit code 0. proceed.
tree in /github/workspace/ChameleonTartu/amazon-mws-fulfillment-inventory-maven/newdata:
+ mkdir -p ghrs-data/snapshots
newdata

0 directories, 0 files
+ cp -a 'newdata/*' ghrs-data/snapshots
cp: cannot stat 'newdata/*': No such file or directory
```

You can see the list of all repos in the [GitHub Action](https://github.com/ChameleonTartu/buymeacoffee-repo-stats/runs/2453463094?check_suite_focus=true).

Do you have any idea? It used to work before, maybe I shouldn't rely on the `@head` branch? :-)

**Comment by jgehrcke** [comment]
Sorry for the late feedback. Thanks for sharing this. I might polish this soon -- but after all, I think this behaves as I originally intended it to behave: when there is no data, don't generate a report. Of course this can be made nicer by rendering a report that indicates in clear English that no data is available yet : ).

**Comment by ChameleonTartu** [comment]
@jgehrcke Thank you for the response. 
Here is an example of the [pipeline](https://github.com/ChameleonTartu/buymeacoffee-repo-stats/actions/runs/781697719) from 25 days ago. It looks fine, green, etc. After a while, some of the pipelines started failing, making me think that they shouldn't fail when there is no data. Shouldn't no data mean zero?

My thought was: _The missing data is the same as no data. Failure should occur when something is wrong._

Also, in **action**, there is no elegant mechanism saying, build report if there is some data.

**Comment by jgehrcke** [comment]
> they shouldn't fail when there is no data.

Yes! When there is no data, the action should not emit an error status; you are right.

When there is no new data, we can either exit early (indicating success) and _not_ regenerate the report, or actually regenerate the report so that at least the "generated on.... " part of the report updates periodically.

I opted for the latter: regenerate the report, even when no new data is there. Corresponding patch: https://github.com/jgehrcke/github-repo-stats/pull/22

**Comment by ChameleonTartu** [comment]
@jgehrcke Thank you for the change. I am dependent on @HEAD, so I receive the latest updates, and it works perfectly now. I tracked for the last week to ensure it.

**Comment by jgehrcke** [comment]
Thank you for the feedback @ChameleonTartu!
