### ISSUE TITLE
Add "dependent" stats

### ISSUE THREAD

**Issue by egil** [jgehrcke/github-repo-stats#19]
For libraries that are used by other projects, it would be awesome if the stats generation could include the dependent stats as well (https://github.com/org/repo/network/dependents).

**Comment by jgehrcke** [comment]
It's a lovely request, and I am so happy about your interest. Realistically, however, I think this would be a rather huge complexity explosion and a lot of work to do nice. Probably out of scope :).

**Comment by egil** [comment]
Fair enough. Feel free to close this issue if it will stay out of scope forever :)

**Comment by jgehrcke** [comment]
"forever" is a strong word -- but nevertheless closing this. For now. :)
