### ISSUE TITLE
Maybe a Typo in README

### ISSUE THREAD

**Issue by subbyte** [jgehrcke/github-repo-stats#20]
The cron job line in README `* 23 * * *` seems to be run every minutes between 11:00PM and 11:59PM according to [crontabguru](https://crontab.guru/#*_23_*_*_*).

The correct syntax could be `0 23 * * *`.

**Comment by jgehrcke** [comment]
Thank you @subbyte that was indeed an oversight; and a really mean one! I have addressed that in #21.
