### ISSUE TITLE
How are unique and totals calculated

### ISSUE THREAD

**Issue by metaclips** [jgehrcke/github-repo-stats#23]
```
[path total unique] filename
[/myrepo/pulls 98 21]       2021-06-05_000958_top_paths_snapshot.csv
[/myrepo/pulls 107 21]      2021-06-06_000436_top_paths_snapshot.csv
[/myrepo/pulls 118 21]      2021-06-07_000430_top_paths_snapshot.csv
```
The above are my collated data for top paths, are the unique and total aggregates. Do I say the `actual` total number of unique views for 2021-06-06 is 0 (21 - 21) and the `actual` total views 9 (107 - 98)

**Comment by metaclips** [comment]
They are aggregates. Closing now.

**Comment by jgehrcke** [comment]
Hey @metaclips! So, each of these snapshots reflects a 14-day period.

More specifically, at any time a snapshot is received from the github API the data that github returns corresponds to an aggregate over a _rolling window_ of 14 days width. The window moves with sub-day precision. That is, with every minute the snapshot is received the outcome may actually change :).

The analysis in github-repo-stats accounts for that.

Also see this code comment: https://github.com/jgehrcke/github-repo-stats/blob/dab4a915b37a7521cd54033a3147daaeb868ec5c/analyze.py#L483

and this code comment: https://github.com/jgehrcke/github-repo-stats/blob/dab4a915b37a7521cd54033a3147daaeb868ec5c/analyze.py#L770
