### ISSUE TITLE
Docker image failing to build

### ISSUE THREAD

**Issue by tcamise-gpsw** [jgehrcke/github-repo-stats#24]
Hey awesome project here. This is going to save me a lot of time!

Unfortunately, your Docker image is failing to build when I run this in my workflow. It looks like pip is failing to get the wheel for matplotlib, so it then tries to build it from source but the Docker image is missing gcc, make, etc so this fails.

I can't explain why pip is failing to find the whl...or how this is working for you. 
However, I am able to work around it by using python:3.8-buster as the base image (instead of slim). This includes all of the necessary build tools and allows me to build matplotlib.

Any ideas on what is going on here?

Ultimately, regardless of the outcome of this, I think the best solution is to pull a pre-built docker image as opposed to building it each time as this would be more reliable and faster. At least, if that's possible...I'm not super well versed with Github actions

**Comment by jgehrcke** [comment]
I have done some work in #25, introducing https://hub.docker.com/r/jgehrcke/github-repo-stats-base.

**Comment by jgehrcke** [comment]
> I can't explain why pip is failing to find the whl...or how this is working for you.

Btw, that was probably because of a platform-specific build. Maybe you had tried this on a fancy new M1 mac?

**Comment by jgehrcke** [comment]
Note that I have merged #25 and when/if you are using the HEAD of this action then you are testing this change. I am doing so via https://github.com/jgehrcke/ghrs-test -- so, let's maybe incubate this for a bit.

**Comment by jgehrcke** [comment]
#25 reduced the duration for step `Build container for action use: '/home/runner/work/_actions/jgehrcke/github-repo-stats/HEAD/Dockerfile` from ~2 minutes to ~35 seconds, based on about five samples.
