### ISSUE TITLE
Show Data Point Value on Hover

### ISSUE THREAD

**Issue by TekWizely** [jgehrcke/github-repo-stats#28]
Greetings !

One of the things I like about GitHub's builtin traffic graph is that I can learn the specific data point value by hovering over the dot on the graph.

I'd appreciate the ability to be able do that on the repo stats graphs.

**Comment by jgehrcke** [comment]
I thought about this, too! Thanks for the report. I think before we 'can' do this, we need to limit the data point density reliably. That probably means dynamic down-sampling depending on the overall time width of the data. Right now we show one data point per day; this seems to become too dense for time periods of O(1 year).

**Comment by jgehrcke** [comment]
Did some tooltip work in https://github.com/jgehrcke/github-repo-stats/pull/37 and https://github.com/jgehrcke/github-repo-stats/pull/38.

**Comment by davidpfarrell** [comment]
Greetings ! So I took `@main` for a ride and really like the tool tips !!

I ended up creating #41 after running into some bugs with repos that don't have any forks.

**Comment by jgehrcke** [comment]
@davidpfarrell with the 1.3.0 release do you think we can close this? :)

**Comment by davidpfarrell** [comment]
> @davidpfarrell with the 1.3.0 release do you think we can close this? :)

YES!  I've been running 1.3.0 since Dec 3 and it seems to be working great - No-fork repos don't crash and I have sweet sweet tool-tip values

Thanks so much for making time for this feature!
