### ISSUE TITLE
Fatal error when repo has no forks

### ISSUE THREAD

**Issue by FrankWPA** [jgehrcke/github-repo-stats#49]
![image](https://user-images.githubusercontent.com/19491161/159269691-14d9c0fd-973b-49c7-84da-6ba54b3b8415.png)
Seems that ghrs-data/forks.csv is not generated or could not be found.

**Comment by jgehrcke** [comment]
@FrankWPA just to confirm: was this really fatal for the action run? (Did the action run fail?)

**Comment by FrankWPA** [comment]
@jgehrcke 
Yes, i tried a few times and couldn't get it working

**Comment by jgehrcke** [comment]
I added a patch to the `main` branch.

**Comment by jgehrcke** [comment]
fixed in https://github.com/jgehrcke/github-repo-stats/releases/tag/v1.4.0
