### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by mdpoleto** [jgehrcke/github-repo-stats#50]
Hi,

First, this tool is amazing. Thank you for developing it. I do have one question though: after setting up my version of ".github/workflows/repostats-for-nice-project.yml", do I need to set up an "action.yml" as well? I did not find the setup explanation very clear. Maybe a simple tutorial with every step could benefit noob users like me.

Thanks!

**Comment by jgehrcke** [comment]
>  do I need to set up an "action.yml" as well?

No, you do not need to do that :). I was just quoting the contents of the file to show the input configuration parameters.

> I did not find the setup explanation very clear. 

I removed the mention of `action.yml` from the main README now. Thank you for the feedback!

**Comment by jgehrcke** [comment]
> Maybe a simple tutorial with every step could benefit noob users like me.

Will think this through, thank you! :)
