### ISSUE TITLE
error: analyze.py returned with code 1 -- exit.

### ISSUE THREAD

**Issue by juanbrusco** [jgehrcke/github-repo-stats#64]
```
220907-19:21:39.615 INFO: read 'top referrer' snapshots (CSV docs)
220907-19:21:39.615 INFO: number of CSV files discovered for *_top_referrers_snapshot.csv: 0
220907-19:21:39.615 INFO: about to deserialize 0 snapshot CSV files
220907-19:21:39.615 INFO: all referrer entities seen: set()
Traceback (most recent call last):
  File "//analyze.py", line 1647, in <module>
    main()
  File "//analyze.py", line [154](https://github.com/juanbrusco/github-repo-stats/runs/8235698251?check_suite_focus=true#step:3:155), in main
    analyse_top_x_snapshots("referrer", gen_date_axis_lim((df_vc_agg,)))
  File "//analyze.py", line 520, in analyse_top_x_snapshots
    dfa = pd.concat(snapshot_dfs)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
+ ANALYZE_ECODE=1
+ set +x
error: analyze.py returned with code 1 -- exit.
```

**Comment by juanbrusco** [comment]
possible solution?
```
cols = ['']
dfq = pd.concat(snapshot_dfs, ignore_index=True) if len(snapshot_dfs) > 0 else pd.DataFrame(columns=cols)
```

**Comment by lawrencebower** [comment]
Hi, I've just tried to get this tool working and Im getting the same error. Does it mean I am doing something wrong, or is it a bug?

I'm guessing I could get hold of the rource code and make the edit you are suggesting to fix it?

Slightly concerned by the lack of response to all the currently opened issues, I'm wondering if this package is no longer supported...

**Comment by jgehrcke** [comment]
> Im getting the same error.

@lawrencebower can you please share your exact log output? (more than just `analyze.py returned with code 1`).

**Comment by jgehrcke** [comment]
> Slightly concerned by the lack of response to all the currently opened issues, I'm wondering if this package is no longer supported...

I think you can relax, you have my support. Thanks for asking :-). I wonder how many serious, open issues you actually counted before typing that comment. Sending best wishes!

**Comment by lawrencebower** [comment]
Sorry! Thanks for your help. 

I'm away from my desk until Tuesday. I got the same "no objects to concatenate" error at the same line as juanbrisco. Also, I got a local copy of the code and applied the fix he suggested and now it's working for me running as a local cronjob. 

I can give you more details when I'm back if needed. 

Thanks again, lawrence

**Comment by Tomansion** [comment]
Hi, I have the same error for some of the newest repos I want to get stats from. I think that this is due to the repo lack of traffic : 
![image](https://user-images.githubusercontent.com/59999324/207061809-f446a793-d131-4212-9618-8ffb5ef8cefb.png)

**Comment by jgehrcke** [comment]
Thanks @Tomansion @lawrencebower @juanbrusco -- I had merged https://github.com/jgehrcke/github-repo-stats/pull/68 to `main` and now also to the `RELEASE` branch with the `v1.4.2` release.
