### ISSUE TITLE
Feature request: provide link to latest report pdf which is guaranteed to open in browser

### ISSUE THREAD

**Issue by olets** [jgehrcke/github-repo-stats#74]
Currently, the "Latest report PDF: report.pdf" links point to the `github.com/owner/repo/raw/` url. In some browsers (e.g. Firefox) that opens in the browser; in some it downloads the file (e.g. Chromium browsers, Safari). When I use a browser which will download the file, I have to click into the `latest-report` directory, and from there open the file. Not a big hardship, but I often forget, and click the README link, and trigger a download I don't want.

Links to `github.com/owner/repo/blob/…` will open in the GitHub browser UI. I'd like a second link in READMEs pointing to the `blob` URL. Then I'd get the same convenience in Chromium/Safari as I do in FF.

**Comment by jgehrcke** [comment]
This is now 'done' via https://github.com/jgehrcke/github-repo-stats/pull/75, of course still needs a release.
